* annotated bibliography

* week 2
** theme: Modeling School Segregation
*** Monarrez, Tomas and Chien, Carina (2021)
**** Dividng Lines: Racially Unequal School Boundaries in Public School Systems
**** Annotation:

This paper evaluates ethnic and racial compositions of neighboring schools to find discontinuities. The question is to what extent do neighboring schools segregate their populations and school resources (such as staffing). The authors find over 2000 pairs of neighborhoring schools that are vastly different from each other in ethnic composition and resources, suggesting that school attendance boundaries (SABs) are drawn in ways that amplify segregation, intentionally or otherwise. They link existing inequalities to those created by the New Deal's Home Owners' Loan Corporation redlining policies using historical maps. While they use SABs extensively, they source their data privately, rather than using the public School Attendance Boundary Survey.

*** Saporito, Salvatore and Van Riper, David (2016)
**** Do Irregularly Shaped School Attendance Zones Contribute to Racial Segregation or Integration?
**** Annotation:

This paper contextualizes the 'school attendance zone' or 'school attendance boundary' (SAB) as a concept in education research and demography. The argues establish the benefits of diverse schools and argue that the drawing of SABS is one of the best tools available to administrators to increase diversity. They operationalize irregularity (as in shapes) and show that the more irregularly drawn (i.e. not rectangular) shapes contribute to school diversity. Compact, rectangular SABs tend to mirror the demographic makeup of the overall city, meaning that a grid of SABs will simply reproduce the existing segregation in the city. SABs which are 'gerrymandered' to be sprawling and irregular can draw students from across different ethnic neighborhoods in the city, resulting in a more diverse school. They use the 2009 SABINS database to show that this pattern largely holds, that irregularly drawn SABs almost always have diverse schools.
* Week 3
** theme: null/incoherent
*** Rey, Sergio J. and Anselin, Luc and Folch, David C. and Arribas-Bel, Daniel and Sastre Gutierrez, Myrna L. and Interlante, Lindsey (2011)
**** Measuring Spatial Dynamics in Metropolitan Areas
**** Annotation

This paper is concerned with advancing the study of spatial dynamics of neighborhoods, as opposed to neighborhood composition; i.e. spatial boundaries of a neighborhood vs. the people that live within it. The authors argue that while both are critical for understanding neighborhood change, the study of spatial boundaries is vastly underinterrogated compared to neighborhood composition. The framework presented ivolves regionalizing census tracts (using a Max-P algorithm) in Metropolitan Statistical Areas for two time periods and then investigating 22 neighborhood characteristic variables from census. Results were examined in the regionalized study area (neighborhoods) and at the /a priori/ level (tracts). The findings suggest that higher density, smaller land area, and more centrally located (centrality) neighborhoods tend to experience the highest degree of change. 

*** Fu, Bojie (2020)
**** Promoting Geography for Sustainability
**** Annotation

This article asks Q1: Which disciplines are most quantitively interact with geography for the purpose of advancing sustainability science; Q2: How to best promote geograpic sciences in transdisciplinary methodologies /public policly/, /urban planninging/. The author collect data on frequencies of 11 words that appear with "geography" + "sustainability" in titles, keywords, and abstracts in publications of the ISI Web of Science from 2010 to 2019. The resulting associations between geography, sustainability are orgazied along different dimmensions, such as research objects, policy areas, and modelling methodology. The author then theorizea and describes 5 distinct spheres of research that geographers could pursue to advance the use of geographical methods into sustainability studies: Geographical processes, Ecosystem services and human wellbeing, Human-Environmental Systems, Sustainable development, and Geo-data and models for sustainability.

* Week 4
** theme: Big Data
goal of the class is to identify a field of subliterature from which to beign disertation
*** Thatcher, Jim and O'Sullivan, David and Mahmoudi, Dillon (2016)
**** Data Colonialism through Accumulation by Dispossession: New Metaphors for Daily Data
**** Annotaiton

This article contributes to theoretical understanding of the role of big data in capitalist production. Through End User License Agreements and myrriad smart devices and sensors, technology firms collect and aggregate data in a way that resembles David Harvey's Accumulation by Dispossession. Individual data points are abstracted away from the "lifeworld" and algorithmicly processed to generalize and predict purchasing and consumption patterns. "Social norms, aesthetic pleasures, and perceived values encourage the use of an increasing array of technologies equipped with sensors that quantify and then communicate data about previously private times and places to third-party actors." This process is termed "data colonialism," to contrast with the framing of technological advancements as "digital frontierism." Further investigation in this area for me is the role of big data in the "filtering" of news and personal information feeds from the basis of the agggregated digital identities created by dispossed data.

*** Crampton, Jeremy W. (2015)
**** Collect It All: National Security, Big Data, and Governance 

This paper provides a study of the complications of the techonological advancement of big data. It draws primarily from examples of consequences drawn from the US Intelligence Agencies (IC) and are primarily divided into two categories: (geo)privacy and algorithmic security. "Big data are a matter of technologic /practices, epistimologies, and ontologies/." The article provides a detailed summary of key facts about the IC revealed by the Snowden documents; personel, budgets, specific operation details, and entertains the legal arguments surrounding things like bulk surveillance and 'incidental collection'. The author argues that corporate activities actively extend the state by increasing its reliance on the private sector; government purchases data, underwrites research, funds operations that increase government's depth of view. The paper touches on uses of big data by the government for warfare, particularly with drones in the war on terrorism. The author provides avenues for future research: Better histories of development of geospatial IC, better accounting for IC operations, better encryption and legal protections (informed consent about government surveillance.

* Week 5
** Laniyonu, Ayobami (2018)
*** Coffee Shops and Street Stops: Policing Practices in Gentrifying Neighborhoods
*** Annotation
This article presents an empirical analysis of the post-industrial policing hypothesis by operationalizing gentrification and applying spatial Durban models in New York City between 2010 and 2014. Spatial Durbin models an outcome of interest as a function of endogenous interaction effects, direct effects, and exogenous interaction effects. Effects are modelled based on differing theories to explain the spatial variation of policing, including rational-beauracratic theory, and conflict theory; racial threat, economic threat. Initial analysis yields support for all of these theories - Effectively, the Durbin modelling reveals that gentrification in a given tract is very strongly associated in increases in policing in neighboring tracts, but negatively associated in itself. As well, these effects vary with the extent of gentrifiation that has occurred - the author distinguishes between tracts inelligable for gentrification, tracts elligable, and post-gentrified tracts. These findings support the notion that police are utilized to drive undesired persons from a given area to make it more ammenible to the in-moving richer, whiter population. The poorer, darker population is corralled and heavily policed in adjacent tracts. Police ramp up their postindustrial policing practices in areas known to be undergoing change (i.e. experienced influx of 'undesirable' people).

** Robert J. Sampson, Stephen W. Raudenbush, Felton Earls (1997)
*** Neighborhoods and Violent Crime: A Multilevel Study of Collective Efficacy
*** Annotation

* Week 6
** Theme: Development Arrested
*** Woods, Clyde (1998)
**** Development Arrested: The Blues and Plantation Power in the Mississippi Delta
**** Annotation
Development Arrested is a seminal work that combines several methodologies to describe the history of development in the region known as the Mississippi Delta. The work is largely concerned with the power structures involved in the creation, action, and dissolution of administrative bodies in the region; but Woods also draws upon the development of culture in the region, and as such this book is also an epistomology of the blues, broadly defined.
*** Isenberg, Alison and Connerly, Charles E. and Lipsitz, George and Wilson, Bobby M. and Thomas, June Manning (2004)
**** [SYMPOSIUM] on Wood's Development Arrested
**** Annotation
*** Tiefenbarcher, John P. (2019)
**** [REVIEW] Development Arrested, The Blues, and Plantation Power In the Mississipi Delta
**** Annotation

* todo

** DeWitt, N. (2022). 
*** Twisted Fate: How California's Premier Environmental Law has Worsened the State's Housing Crisis, and How to Fix it. 
*** Annotation

** Schmidt-Traub, Guido and Kroll, Christian and Teksoz, Katerina and Durand-Delacr, David and Sachs, Jeffrey D. (2017)
*** National Baselines for the Sustainable Development Goals Assessed in the SDG Index and Dashboards
*** Annotation
