Geography 701: Development of Geographic Thought
Seminar by Stuart Aitken, Trent Biggs
[[https://sdsu.instructure.com/courses/113619][link to Canva website]]

* Notes
** 8/22/2022 :week1:
*** first half of class a discussion of the readings
**** 'jigsaw' activity with articles
**** focus of class is to write a broad lit review of thesis
**** using class to streamline thesis process
**** by end of course, will have a annotated bib with 30 refs, springboard to thesis
*** Get started on
**** Entrance interview with advisor
***** Some overlap with phd entrance interview
**** Colloquium summaries
***** 1 page, 4 required
***** listed online on geography.sdsu website
*** The annotated bibliography will get some work each week
**** Read and write about two articles each week in a document
**** Link the document to SA and TB spreadsheet (on canva)
***** They can read it whenever to check progress
***** Other students can look, too.
*** Steps to understanding an article
    1. Whats the (research) question?
    2. Whats the method used to answer the question?
    3. What's the answer to the question?
*** for next week
**** task read and reflect using prompts from canva
***** todo read nrc (national research council) report :reading:
****** part 1
******* purpose is to formulate a short list (11) of high priority research questions in geographical science that are relevant to societal needs. these can be grouped as:

       1. how to understand and respond to environmental change?
       2. How to promote sustainability?
       3. How to recognize and cope with the rapid spatial reorganization of economy and society?
       4. How to leverage technological change for the betterment of society and environment?

******** nrc committee used criteria to forumlate research directions:

       - clear societal significance
       - must be central to core geographic concepts
       - must relate clearly to agendas of larger scientific community
       - must be tractable (demonstratable)
       - must be answerable using existing data or methods
******* "geographical sciences are about more than simply mapping, rooted in concern with the interaction of phenomena and systems treated as distinct." :quote:
******* Central feature of geographical sciences is the recognition that local/regional circumstances affect larger scale processes.
******* explosive growth of geographical data and technology results in multi-investigator, transdisciplinary projects.
****** part 2
******* explores each of these questions in depth. summarizes the state of current research and describes potential roles and contribution of geographic sciences
****** part 3
deals with how to move forward to address the goals listed in part 2.
Technological and infrastructure challeneges, many of which will have progressed greatly in the time since the report was published, as well as ways to train new geographers and perform outreach to people in positions of power who may be unaware of the depth of information offered by geographical techniques. 
***** TODO Read Cutter (2001) :reading:
****** NYT guy asks, Why do geographers suck? missing the 'big picture issues' in their research?
******* 'academic culture' problem?
	+ social structure of geographers leads to quick investigations that lead to publications/tenure
	+ geographers scattered, difficult to rally around large research issues
	+ AAG should create new incentive structures (don't generalize contributions, encourage recognition)
******* Deeply held human need to create boundaries, divide space?
        + consequences of human development, environmental degredation, exasperation of inequality, suburbanization and isolation from community
******* link between physical deliniations and our perception of space
	 - public vs private
	 - interactions and sense of community
	 - Map of US with states vs water basins
	   - examine water networks through the actual networks or the bodies that control them with policy? 
******* /strained/ Thomas Jefferson conclusion
         - written in 2002
***** TODO Write 
**** TASK [#B] Read Critiques
**** TASK Biosketch/photo
*** Action items
**** TASK Follow up with SA about 'Media Geography'
<<<<<<< HEAD
** 8/29/2022 :week2:
*** Course Mechanics
**** Skipping week 3 (labor day) 
=======
what is media geography and is it connected to propaganda?
***** TODO what readings
****** 
>>>>>>> 9105a6e7a861fb3c6d8673b6385cd6b826ff2b42
