* Geography 701: Development of Geographic Thought Seminar
- San Diego State University
- Fall 2022
** Instructors: Stuart Aitken, Trent Biggs
** [[https://sdsu.instructure.com/courses/113619][Link to Canvas website]]

* Syllabus
** Course purpose

The primary purpose of this seminar is to engender a sense of what
contemporary geographers are doing, and how they come to be doing it.
We will discuss and debate issues relating to philosophy and theory in
the discipline, and how academic geographers contribute to the
professions, the sciences, the arts, and society in general.  As a
professional geographer, no matter what subfield you adhere to, it is
important that you have an understanding of how geographic knowledge
is produced; this entails an engagement with philosophies, theories
and methodologies. The seminar focuses on informed discussion of
readings that are chosen to illustrate, explain and offer a critical
perspective of the discipline’s development without losing sight of
tensions and accommodations between different ways of knowing. The
secondary focus of the seminar is to help you build a bibliography for
your future thesis work, and a third focus is to introduce you to
other graduate students in your cohort.  By so doing, we hope that a
sense of community is created between you as members of an incoming
graduate class, and between you and faculty members, as intellectual
peers with shared interests, goals and ways of knowing the world.

Throughout the seminar, we will discuss the philosophical, theoretical
and methodological underpinnings of contemporary geography. You will
confront complex ideas and conceptual approaches, some of which will
appear contradictory, and you will come to appreciate how new bodies
of knowledge coalesce and evolve.  Although we will consider
methodologies, the applied aspect of the field will not be a specific
focus of our discussions, with the admonition that is difficult to
debate the usefulness of geography without reference to its practice
the "real" world.

The annotated bibliography and literature review that you will build
in this course are designed to contribute directly towards your thesis
proposal work in the spring semester in GEOG 700.

** Learning objectives

1. Summarize and discuss the philosophical, theoretical and
   methodological underpinnings of contemporary geography, including
   physical, human, and geographic information science.

2. Find and summarize major historical and contemporary research in
   your subfield of geography.

3. Synthesize the major research questions and/or debates in your
   subfield in written and verbal form.

** Schedule

| Week # | Date | Topic |
 
*** I. The Emerging Field

| 1 | Aug 22  | Introductions and course overview (TB)                |
| 2 | Aug 29  | What is geography and how do we think about it?  (TB) |
| 3 | Sept 05 | LABOR DAY                                             |
| 4 | Sept 12 | Changing ways of thinking (SA)                        |

*** II. Explanatory and Interpretative Thinking

| 5 | Sept 19 | The quantitative revolution and the rise of positivism (SA) | 
| 6 | Sept 26 | Physical Geography:  philosophical underpinnings (TB)       | 
| 7 | Oct 03  | Humanism and connections to the arts and humanities (SA)    | 
| 8 | Oct 10  | Complex systems and models in geography (TB)                | 
| 9 | Oct 17  | GIS and society (TB)                                        | 

*** III. Critical Thinking

| 10 | Oct 24 | Marxism, feminism, and post-colonialism/anti-racism (SA)          |
| 11 | Oct 31 | Environmentalism, Political Ecology, Critical Phys Geog (TB)      |
| 12 | Nov 7  | Relational, post-structural, and more-than-human geographies (SA) |
| 13 | Nov 14 | Protesting 701                                                    |
 
*** IV.  Literature Reviews on Chosen Subfields

| 14 | Nov 21 | Thanksgiving Week     |
| 15 | Nov 28 | Student presentations |
| 16 | Dec 5  | Student presentations |
 
** Course design and assignments

*** Biographical Sketch and Photograph

As a way to introduce ourselves we’ve reserved some space on Canvas
for you to upload a biographical sketch and photograph. In your
bio-sketch please include your name, where you did your undergraduate
and MS/MA degree (if applicable). Tells us a little about your
background in geography and your current research interests.  One or
two paragraphs is sufficient for the biosketch and don’t forget your
photograph (perhaps showing you doing something that you consider
geographic). Due by the second week of the semester (see schedule for
submission details).  5% of grade.

*** Entrance Interview with Thesis Advisor

This exercise requires you to meet with your Thesis Advisor to discuss
your goals for your program at SDSU.  Due by the fourth week of the
semester (see schedule for submission details).  5% of grade

*** Epitome Paper

As part of your review of the literature in your area of interest, you
are going to come across many interesting articles (I hope). I want
you to choose one (just one) of the geography articles that epitomizes
your interests in the discipline from a philosophical or theoretical
basis (see text books for working definitions of philosophy and
theory). Write a 1-2 page persuasive essay entitled “the best example
of a geographical paper …” focusing on the theoretical and
philosophical basis of the article as well as your own views and
opinions (see ‘seminar policies and procedures’ for details on writing
papers). One other person from the class will be asked to review and
critique your epitome paper for its geographic content as part of our
discussion on Week 7.  10% of grade.

*** Annotated Bibliography and Concept Map

Each week you will read two articles *selected by you with consultation
with you advisor* and briefly write about their content.  During
break-out sessions, we’ll discuss your annotated bibliographies.  By
the end of the semester you will have (at least) 30 articles.  You
will create and present a Concept Map of the Annotated Bibliography.
Some of these will become part of the reference list for your
literature review .  15% of grade.

*** Literature Review

The literature review paper is focused on your area of interest (and
to a much lesser extent, your research questions), and make a case for
further investigation and research, highlighting gaps in knowledge and
asking questions that need to be answered for the betterment of the
discipline; as such, its contents are selected to make the case.  It
is not an annotated bibliography, but a synthesis.  Lit review papers
are to be 8-10 pages in length and should follow the format of
‘progress reports’ in either Progress in Physical Geography
(http://ppg.sagepub.com) or Progress in Human Geography
(http://phg.sagepub.com Links to an external site.) (see ‘seminar
policies and procedures’ for details on writing papers).  The first
draft of the lit review paper is for peer review, which will not be
graded by the instructor but by your peer (NO extensions are given on
this due date).  You will submit a revised version based on the peer
reviews and feedback from your oral presentation on exam week. 20% of
grade.

**** Double ‘Blind’ Review

Your progress paper will be submitted to a double-blind peer review
process.  That is, each of you is expected to critically review two of
your colleagues' papers and assess whether or not they are
publishable.  We will talk about a format for doing this later on in
the semester.  Due by the thirteenth week of semester (see schedule
for submission details). 10% of grade

**** Oral Presentation

You will present your revised lit review paper in a series of sessions
to be run during the scheduled class time.  The sessions will emulate
those at the annual meetings of the American Association of
Geographers.  10% of grade

*** Colloquium Summaries

Attendance at the Department of Geography’s Colloquium Series (mostly
Friday afternoons but also other times) is a required part of the
seminar.  Write a 1-2 page concise and critical reflection on four of
the colloquium presentations you attend. You should make connections
between what is presented relative to what you are learning about
geographic thought in the seminar. See ‘Seminar Policies and
Procedures’ for further instructions.  Due throughout the semester
with everything submitted by Week 15.  10% of grade (2.5% of the final
grade each)

*** Seminar Attendance, Preparation and Participation

You are required to read many, many articles most weeks. Besides
regular attendance and participation, you will be asked to participate
in jigsaw discussions. For these discussions, you are required to read
assigned articles and be prepared to comment on colleagues'
critiques. 10% of grade

*** Seminar Policies and Procedures

*** Weekly attendance and participation

You are expected to come to class prepared to discuss all assigned
readings. The seminar meets in person once a week. There will be a
15-20 break each class period, at about the half-way mark. Make every
effort to be in the classroom at the scheduled beginning times
(including after the break) and plan on staying until the seminar
ends. Repeated arrivals/ departures from the seminar are discouraged
and will negatively affect your final grade.

Please talk to us if you are having difficulties completing an
assignment, but do not wait until it is too late.

*** Colloquium summaries

These should be 1-2 pages, using the same formatting guidelines
describe above for papers. I suggest you submit at least 2 summaries
by the end of the Week 9 and any remaining ones prior to the end of
classes (Week 15) The following questions can be used as inspiration
to write your colloquia summaries, but you can structure your summary
as you wish and expand beyond this:

What theories and schools of thought inspired the presentation?  What
areas, sub-disciplines and geographic concepts were key to the
presentation?  What were the strengths and weakness of the
presentation in relation to geographic thinking?  In what ways was the
presentation explicitly or implicitly geographical (or not)?  What did
you learn and how did it help you expand your understanding of
geographic thinking?

